### ISSUE TITLE
功能请求：数据统计

### ISSUE THREAD

**Issue by behinder85** [jayzcoder/TrguiNG#1]
像[transmission-web-control](url=https://github.com/transmission-web-control/transmission-web-control)一样可以统计
当前会话的上传和下载量以及全局的上传量、下载量、会话次数等

**Comment by jayzcoder** [comment]
功能有的，搁这
![image](https://github.com/jayzcoder/TrguiNG/assets/32261474/03062def-4836-4d91-8854-7d23ee1427d9)
