### ISSUE TITLE
TrguiNG_1.2.0_240417a_x64-setup.exe电脑连接失败

### ISSUE THREAD

**Issue by wuvnnn** [jayzcoder/TrguiNG#10]
![360截图20240421114850393](https://github.com/jayzcoder/TrguiNG/assets/101920312/e2eb0bca-6570-467f-96bf-c70224ce9a55)
配置页面进不去，原版TrguiNG_1.3.0装完可以进去

**Comment by monsoon585** [comment]
我也是

**Comment by 1983sxj** [comment]
路过，同样，1.3.0可以的，可惜没汉化

**Comment by jayzcoder** [comment]
> 我也是
> 路过，同样，1.3.0可以的，可惜没汉化

下版更新

**Comment by jayzcoder** [comment]
已发布
