### ISSUE TITLE
底部“剩余空间”显示异常

### ISSUE THREAD

**Issue by zhaoyibo** [jayzcoder/TrguiNG#11]
<img width="179" alt="image" src="https://github.com/jayzcoder/TrguiNG/assets/11988080/ee21dc03-77c5-4ff9-a805-bc587670040b">

版本：trguing-web-v1.2.0-zh-240417a
我的 tr 是在 nas 的 docker 里，挂载了两个下载目录：
```
    volumes:
      - /share/Downloads:/downloads
      - /share/Downloads4:/downloads4
```

不知道这里显示异常是不是与部署方式有关。

在参数设置里边，有“默认保存目录”，是不是可以以此根目录为准显示剩余空间容量？
<img width="519" alt="image" src="https://github.com/jayzcoder/TrguiNG/assets/11988080/111dd838-edcc-45d6-8114-9b7087d6b94b">

**Comment by jayzcoder** [comment]
剩余空间是通过tr提供的rpc接口获取，检查tr相关设置，确保默认保存目录存在（不存在时会返回-1）

**Comment by zhaoyibo** [comment]
明白了。
我这个是因为 tr 配置文件里的默认下载路径和界面上配置的默认下载路径不同，就会显示 -1，设置成一致的，就正常显示了。
