### ISSUE TITLE
自定义字段设置无法保存

### ISSUE THREAD

**Issue by lizhenujs** [jayzcoder/TrguiNG#17]
比如调整名称长度，勾选服务器状态后，刷新浏览器又恢复默认，不知道有没有办法解决

**Comment by jayzcoder** [comment]
> 比如调整名称长度，勾选服务器状态后，刷新浏览器又恢复默认，不知道有没有办法解决

我用的edge，都正常，检查下浏览器设置。

**Comment by lizhenujs** [comment]
也是edge，各种清除数据无效，最后退出重新登录微软账户才正常
