### ISSUE TITLE
希望支持-侧边栏收缩

### ISSUE THREAD

**Issue by gxterry** [jayzcoder/TrguiNG#19]
感谢大佬辛苦开发，UI非常棒！
个人请求支持 
1.字体大小调整
2.侧边栏 标签列表 、服务器列表、报错列表 收缩 （因为站比较多&标签比较多的情况下.....列表真的好长）

再次感谢开发大佬

**Comment by tasty007** [comment]
是个不错的想法

**Comment by jayzcoder** [comment]
侧边栏右键可设置要展示的项，按住右侧可拖动调整展示顺序
如图：
![image](https://github.com/jayzcoder/TrguiNG/assets/32261474/f1e0ec0e-b744-4258-9a89-dfacf633e305)
