### ISSUE TITLE
功能需求：点击数据目录时，在列表中不显示子目录下的种子

### ISSUE THREAD

**Issue by TimoYoung** [jayzcoder/TrguiNG#20]
按数据目录筛选时，只显示当前目录下的种子,排除子目录下的，下载目录层级较多时非常有用，可参考transmission-web-control中的hide-subfolders，在其他设置中增加一个checkbox。不知道好不好实现。感谢大佬~

**Comment by jayzcoder** [comment]
这功能好像有点用
