### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by QRQF001** [jayzcoder/TrguiNG#28]
1】webui界面添加种子时，对于拖拽多个种子需要每个单独设置，能否批量设置
2】这个宽度可以调节，但是不能左右换位置，就是不能把已上传 移到 已下载左侧
![【2024-05-05 01-22-27】](https://github.com/jayzcoder/TrguiNG/assets/62094806/d070a0a3-590e-4dff-bc49-354de61faf5c)

3】移动进度条，顶部列表不跟着种子走
![【2024-05-05 01-24-53】](https://github.com/jayzcoder/TrguiNG/assets/62094806/a4ab0a0c-f64d-4516-8b08-9c12a7cf2a46)

**Comment by jayzcoder** [comment]
1. 待更新（最近有点忙，可能要晚点了）
2. 表头右键，右边摁住拖动可调整位置
![image](https://github.com/jayzcoder/TrguiNG/assets/32261474/04445e9e-0b3d-4f29-9125-0723f01472e4)
3. 试了下没这个问题，可以清空浏览器缓存或者换浏览器试试？

**Comment by jayzcoder** [comment]
240607a 已更新
