### ISSUE TITLE
选择下载位置出错

### ISSUE THREAD

**Issue by Juhraya** [jayzcoder/TrguiNG#29]
win11，用磁盘映射，映射debian的smb为Z盘，添加种子，选择保存路径为Z:\Uploads（如图1） ，点击确认后，系统自动省略掉了一个"/"，变成了/mntUploads
<img width="269" alt="1715002988703" src="https://github.com/jayzcoder/TrguiNG/assets/60544314/e423abfd-4556-493d-8b77-87ff3452b6d6">
<img width="589" alt="1715003004631" src="https://github.com/jayzcoder/TrguiNG/assets/60544314/b819d8b4-5dd2-478f-a9a4-859061f9d014">

tr4.0，docker部署，compose文件里已有“      - /mnt/Uploads:/mnt/Uploads”的映射。

**Comment by jayzcoder** [comment]
![image](https://github.com/jayzcoder/TrguiNG/assets/32261474/5c7e4b1e-8e9e-4441-9717-83983d7c43fa)
检查路径映射中remote是否漏了后面的斜杠
