### ISSUE TITLE
在手机端上用的时候，显示页面出错了

### ISSUE THREAD

**Issue by liuwaha** [jayzcoder/TrguiNG#35]
往右移动会出现空白，没办法显示后面的内容，恳请大佬优化，谢谢
![Screenshot_2024-05-28-19-56-03-437_com kiwibrowser browser-edit](https://github.com/jayzcoder/TrguiNG/assets/150313983/0524ae76-fe23-4a4e-8e8b-055be98d2b64)

**Comment by jayzcoder** [comment]
需要原作者适配手机端，估计是不会适配的
