### ISSUE TITLE
能否增加一个上传的总计

### ISSUE THREAD

**Issue by chenuon** [jayzcoder/TrguiNG#37]
我记得以前老皮肤有，这个新皮肤没这个统计，能否在左侧目录下面，增加一个栏位，显示当日上传小计，和一个从运行开始的上传总计。

**Comment by chenuon** [comment]
哦。找到了。可以关闭话题了。谢谢

**Comment by hfgj** [comment]
麻烦问下在哪呢，我也是找了半天没找到

**Comment by chenuon** [comment]
右下角，上面一点点，有个 数据统计

2024-06-15 

69395866 



发件人：hfgj ***@***.***>
发送时间：2024-06-15 12:59
主题：Re: [jayzcoder/TrguiNG] 能否增加一个上传的总计 (Issue #37)
***@***.***>
***@***.***>,"State ***@***.***>

麻烦问下在哪呢，我也是找了半天没找到
