### ISSUE TITLE
实际下载和已下载弄反了（更新了事例截图）

### ISSUE THREAD

**Issue by 54dimeng** [jayzcoder/TrguiNG#6]
实际下载和已下载是不是弄反了？
现况是：实际下载显示已经完成的数据大小，已下载显示选中文件的大小

**Comment by jayzcoder** [comment]
已下载指的是本地文件大小
实际下载指的是通过tr下载的大小，转种和辅种的都会是 0

**Comment by 54dimeng** [comment]
以下面这个任务为例，种子文件总大小38.51GB，选定了2个文件大小10.02GB，下载了10.02GB的3.1%共计
321.2MB，现在本地文件的大小为321.2MB。
因此321.2MB可描述为**实际下载**或者**已下载**（建议描述为**已下载**，和**已上传**作对应）
将10.02GB描述为**已下载**不合适，建议描述为**选定大小**或者**已选择**
![screenshot-1713794910805](https://github.com/jayzcoder/TrguiNG/assets/140787592/126b689a-f82e-4779-8b2b-e155c7e43986)
