### ISSUE TITLE
请问如何还原到原版皮肤

### ISSUE THREAD

**Issue by jukxi** [jayzcoder/TrguiNG#67]
群辉套件版，有的功能好像找不到，想还原到原版ui看看，找不到入口

**Comment by eaglexxxm** [comment]
> 1.Download latest trguing-web-xxxx.zip zip from releases page.
2.Unpack it anywhere, make sure that the user transmission runs under (by default debian-transmission) has read permissions.
3.Edit transmission daemon systemd unit file /etc/systemd/system/multi-user.target.wants/transmission-daemon.service and add following to [Service] section:
Environment=TRANSMISSION_WEB_HOME=/path/to/extracted/trguing/zip
4.Reload the unit file with sudo systemctl daemon-reload and restart the service sudo systemctl restart transmission-daemon

按第3、4步应该能解决。
