### ISSUE TITLE
如果属性和任务窗口能折叠就更好了

### ISSUE THREAD

**Issue by 54dimeng** [jayzcoder/TrguiNG#9]
如果属性和任务窗口能折叠就更好了，不过可能原版就无此功能

**Comment by jayzcoder** [comment]
![image](https://github.com/jayzcoder/TrguiNG/assets/32261474/16f5887c-f219-4886-b7ae-e30943c2e51d)

右上角可以控制，左下角状态框下版增加控制项

**Comment by 54dimeng** [comment]
看到啦，原来在这里，谢谢～～
